import { create } from 'zustand';
import { ChatMessage, ToolCallRecord, ArtifactRecord, AttachedFileRecord } from '../types/grok';

// State for a single open thread tab
export interface ThreadState {
  threadId: string;        // UUID generated by frontend
  sessionId?: string;      // grok session_id (set after TurnComplete)
  workspaceId?: string;
  cwd: string;
  title: string;
  messages: ChatMessage[];
  status: 'idle' | 'running' | 'error';
  errorMessage?: string;
}

interface AgentStore {
  // Open thread tabs
  threads: ThreadState[];
  // Currently active thread tab
  activeThreadId: string | null;

  // Actions
  openThread: (thread: Omit<ThreadState, 'messages' | 'status'>) => void;
  closeThread: (threadId: string) => void;
  setActiveThread: (threadId: string) => void;

  // Message actions
  addUserMessage: (threadId: string, content: string, attachedFiles?: AttachedFileRecord[]) => string;  // returns message id
  appendAssistantDelta: (threadId: string, delta: string) => void;
  appendThinkingDelta: (threadId: string, delta: string) => void;
  finalizeAssistantMessage: (threadId: string) => void;

  // Tool call actions
  addToolCall: (threadId: string, msgId: string, tool: ToolCallRecord) => void;
  updateToolResult: (threadId: string, toolId: string, output: string, exitCode?: number, isError?: boolean) => void;

  // Artifact actions
  addArtifact: (threadId: string, artifact: ArtifactRecord) => void;

  // Status actions
  setThreadStatus: (threadId: string, status: ThreadState['status'], error?: string) => void;
  setSessionId: (threadId: string, sessionId: string) => void;
}

let msgIdCounter = 0;
const newId = () => `msg-${Date.now()}-${msgIdCounter++}`;

export const useAgentStore = create<AgentStore>((set) => ({
  threads: [],
  activeThreadId: null,

  openThread: (thread) => {
    set((s) => ({
      threads: [...s.threads, { ...thread, messages: [], status: 'idle' }],
      activeThreadId: thread.threadId,
    }));
  },

  closeThread: (threadId) => {
    set((s) => {
      const threads = s.threads.filter((t) => t.threadId !== threadId);
      const activeThreadId =
        s.activeThreadId === threadId
          ? threads[threads.length - 1]?.threadId ?? null
          : s.activeThreadId;
      return { threads, activeThreadId };
    });
  },

  setActiveThread: (threadId) => set({ activeThreadId: threadId }),

  addUserMessage: (threadId, content, attachedFiles) => {
    const id = newId();
    set((s) => ({
      threads: s.threads.map((t) =>
        t.threadId !== threadId ? t : {
          ...t,
          messages: [...t.messages, {
            id, role: 'user', content, thinking: '',
            toolCalls: [], artifacts: [],
            attachedFiles: attachedFiles ?? [],
            createdAt: Date.now(),
          }],
        }
      ),
    }));
    return id;
  },

  appendAssistantDelta: (threadId, delta) => {
    set((s) => {
      const threads = s.threads.map((t) => {
        if (t.threadId !== threadId) return t;
        const messages = [...t.messages];
        const last = messages[messages.length - 1];
        // If last message is already assistant, append to it
        if (last && last.role === 'assistant') {
          messages[messages.length - 1] = { ...last, content: last.content + delta };
        } else {
          // Start new assistant message
          messages.push({
            id: newId(), role: 'assistant', content: delta, thinking: '',
            toolCalls: [], artifacts: [], attachedFiles: [], createdAt: Date.now(),
          });
        }
        return { ...t, messages };
      });
      return { threads };
    });
  },

  appendThinkingDelta: (threadId, delta) => {
    set((s) => {
      const threads = s.threads.map((t) => {
        if (t.threadId !== threadId) return t;
        const messages = [...t.messages];
        const last = messages[messages.length - 1];
        if (last && last.role === 'assistant') {
          messages[messages.length - 1] = { ...last, thinking: last.thinking + delta };
        } else {
          // Start new assistant message with thinking
          messages.push({
            id: newId(), role: 'assistant', content: '', thinking: delta,
            toolCalls: [], artifacts: [], attachedFiles: [], createdAt: Date.now(),
          });
        }
        return { ...t, messages };
      });
      return { threads };
    });
  },

  finalizeAssistantMessage: (_threadId) => {
    // Current implementation: no-op (message already accumulated via deltas)
  },

  addToolCall: (threadId, _msgId, tool) => {
    set((s) => ({
      threads: s.threads.map((t) => {
        if (t.threadId !== threadId) return t;
        const messages = [...t.messages];
        const last = messages[messages.length - 1];
        if (last && last.role === 'assistant') {
          messages[messages.length - 1] = {
            ...last,
            toolCalls: [...last.toolCalls, tool],
          };
        }
        return { ...t, messages };
      }),
    }));
  },

  updateToolResult: (threadId, toolId, output, exitCode, isError) => {
    set((s) => ({
      threads: s.threads.map((t) => {
        if (t.threadId !== threadId) return t;
        return {
          ...t,
          messages: t.messages.map((m) => ({
            ...m,
            toolCalls: m.toolCalls.map((tc) =>
              tc.id !== toolId ? tc : {
                ...tc, output, exitCode, isError: isError ?? false,
                status: isError ? 'error' : 'done',
              }
            ),
          })),
        };
      }),
    }));
  },

  addArtifact: (threadId, artifact) => {
    set((s) => ({
      threads: s.threads.map((t) => {
        if (t.threadId !== threadId) return t;
        const messages = [...t.messages];
        const last = messages[messages.length - 1];
        if (last && last.role === 'assistant') {
          messages[messages.length - 1] = {
            ...last,
            artifacts: [...last.artifacts, artifact],
          };
        }
        return { ...t, messages };
      }),
    }));
  },

  setThreadStatus: (threadId, status, error) => {
    set((s) => ({
      threads: s.threads.map((t) =>
        t.threadId !== threadId ? t : { ...t, status, errorMessage: error }
      ),
    }));
  },

  setSessionId: (threadId, sessionId) => {
    set((s) => ({
      threads: s.threads.map((t) =>
        t.threadId !== threadId ? t : { ...t, sessionId }
      ),
    }));
  },
}));
